name: Sync with Perforce.

on:
  # Updates every day at 00.00 PST/07.00 UTC.
  schedule:
    - cron: '0 7 * * *'
  # Manually call the workflow.
  workflow_dispatch:

jobs:
  # P4V login.
  update:
    runs-on: ubuntu-latest
    name: update
    
    env:
      P4PORT: ${{ secrets.P4PORT }}
      P4USER: ${{ secrets.P4USER }}
      P4PASSWD: ${{ secrets.P4PASSWD }}
    
    steps:
      # Checkout assets stored in GitHub.
      - name: checkout
        uses: actions/checkout@v2
          
      # Run trust only if your P4PORT includes "ssl:".
      - name: p4 trust
        uses: perforce/setup-p4@v1
        with:
          command: trust
          
      # Authenticate to Helix Core using P4PSSWD GitHub Secret.
      - name: p4 login
        uses: perforce/setup-p4@v1
        with:
          command: login

      # Create a workspace.
      - name: p4 client
        uses: perforce/setup-p4@v1
        with:
          command: client
          arguments: -i
          spec: |
            Client:	github-actions-p4
            Owner:	${{ secrets.P4USER }}
            Root:	$GITHUB_WORKSPACE
            Options:	allwrite nocompress unlocked modtime rmdir
            SubmitOptions:	leaveunchanged
            LineEnd:	local
            View:
              //AGP/20223-20231/GrandmaGreen/GrandmaGreen/Assets/_GrandmaGreen/Scripts/... //github-actions-p4/Scripts/...

      # Pull down assets from Helix Core.
      - name: p4 sync
        uses: perforce/setup-p4@v1
        env:
          P4CLIENT: github-actions-p4
        with:
          command: sync
      
      # Sync new changes to the /Scripts folder.
      - name: commit script changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '/home/runner/work/GrandmaGreenDocumentation/GrandmaGreenDocumentation/Scripts'
          cwd: './Scripts'
          default_author: user_info
          pathspec_error_handling: exitAtEnd
          push: true
          
      # Log out of Perforce.
      - name: p4 logout
        uses: perforce/setup-p4@v1
        with:
          command: logout
