name: Sync Perforce update

on:
  # Updates every day at 00.00 PST/07.00 UTC.
  schedule:
    - cron: '0 7 * * *'
  # Manually call the workflow.
  workflow_dispatch:

jobs:
  # P4V login.
  update:
    runs-on: ubuntu-latest
    name: update
    
    env:
      P4PORT: ${{ secrets.P4PORT }}
      P4USER: ${{ secrets.P4USER }}
      P4PASSWD: ${{ secrets.P4PASSWD }}
    
    steps:
      # Checkout assets stored in GitHub.
      - name: checkout
        uses: actions/checkout@v2
        
      # Set up Python.
      - name: set up python
        uses: actions/setup-python@v2
        
      - run: git clone https://github.com/git/git.git git_source_path
      
      - run: ln -s git_source_path/contrib/fast-import/git-p4 /usr/bin/git-p4
        
      - name: run git-p4 script
        run: |
          python git-p4.py
        
      - name: verify information
        run: git p4 info
        
      - name: login
        run: git p4 login
        
