name: Sync Perforce update

on:
  # Updates every day at 12AM PST/7AM UTC.
  schedule:
    - cron: '0 7 * * *'
  # Manually call the workflow.
  workflow_dispatch:

jobs:
  # P4V login.
  update:
    runs-on: ubuntu-latest
    name: update
    
    env:
      P4PORT: ${{ secrets.P4PORT }}
      P4USER: ${{ secrets.P4USER }}
      P4PASSWD: ${{ secrets.P4PASSWD }}
    
    steps:
      # Checkout assets stored in GitHub.
      - name: checkout
        uses: actions/checkout@v2
        
      - name: verify information
        run: git p4 info
        
      - name: login
        run: git p4 login
        
