name: Sync Perforce update

on:
  # Updates every day at 12AM PST/7AM UTC.
  schedule:
    - cron: '0 7 * * *'
  # Manually call the workflow.
  workflow_dispatch:

jobs:
  # P4V login.
  update:
    runs-on: ubuntu-latest
    name: update
    
    env:
      P4PORT: ${{ secrets.P4PORT }}
      P4USER: ${{ secrets.P4USER }}
      P4PASSWD: ${{ secrets.P4PASSWD }}
    
    steps:
      # Checkout assets stored in GitHub.
      - name: checkout
        uses: actions/checkout@v2
          
      # Run trust only if your P4PORT includes "ssl:"
      - name: p4 trust
        uses: perforce/setup-p4@v1
        with:
          command: trust
          
      # Authenticate to Helix Core using P4PSSWD GitHub Secret
      - name: p4 login
        uses: perforce/setup-p4@v1
        with:
          command: login

      # Create a workspace.
      - name: p4 client
        uses: perforce/setup-p4@v1
        with:
          command: client
          arguments: -i
          spec: |
            Client:	github-actions-setup-p4
            Owner:	${{ secrets.P4USER }}
            Root:	/tmp
            Options:	noallwrite noclobber nocompress unlocked modtime rmdir
            SubmitOptions:	leaveunchanged
            LineEnd:	local
            View:
              //CTIN_484/20221/18406/Jamie_Gianna/our_project_attempt_2/Assets/Scripts/... //github-actions-setup-p4/CTIN_484/20221/18406/Jamie_Gianna/our_project_attempt_2/Assets/Scripts/...

# //AGP/20223-20231/GrandmaGreen/GrandmaGreen/Assets/_GrandmaGreen/Scripts/... //github-actions-setup-p4/AGP/20223-20231/GrandmaGreen/GrandmaGreen/Assets/_GrandmaGreen/Scripts/...

      # Pull down assets from Helix Core.
      - name: p4 sync
        uses: perforce/setup-p4@v1
        env:
          P4CLIENT: github-actions-setup-p4
        with:
          command: sync
          
      - name: p4 copy
        uses: perforce/setup-p4@v1
        env:
          P4CLIENT: github-actions-setup-p4
        with:
          command: copy
          arguments: //github-actions-setup-p4/CTIN_484/20221/18406/Jamie_Gianna/our_project_attempt_2/Assets/Scripts/... $GITHUB_WORKSPACE/ScriptsTest/...
          working_directory: $GITHUB_WORKSPACE/
